CREATE TABLE [dbo].[LoadDirectory]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ComputerName] NVARCHAR(260) NOT NULL DEFAULT 'NUL', 
    [FullPath] NVARCHAR(260) NOT NULL DEFAULT 'NUL', 
    [FirstScanDate] DATETIME2 NOT NULL DEFAULT SYSDATETIME(), 
    [LastScanDate] DATETIME2 NOT NULL DEFAULT SYSDATETIME(), 
    [MyRowVersion] ROWVERSION NOT NULL
)
